### ISSUE TITLE
Split implementations of FeeHandlerWithOracle

### ISSUE THREAD

**Issue by MakMuftic** [sygmaprotocol/sygma-solidity#122]
Separate fee handler with oracle contracts for evm, substrate, and generic message passing as separate implementations.

## Implementation details

Currently, we have this logic inside _FeeHandlerWithOracle_:
```
if(oracleMessage.msgGasLimit > 0) {
    // txCost = dstGasPrice * oracleMessage.msgGasLimit * Base Effective Rate (rate between base currencies of source and dest)
    txCost = oracleMessage.dstGasPrice * oracleMessage.msgGasLimit * oracleMessage.ber / 1e18;
} else {
    // txCost = dstGasPrice * _gasUsed * Token Effective Rate (rate of dest base currency to token)
    txCost = oracleMessage.dstGasPrice * _gasUsed * oracleMessage.ter / 1e18;
}
```

that determines if the processed message (deposit request) is just a basic token transfer or a generic message (`msgGasLimit` > 0). 

This approach allows users to do funky things like set this `msgGasLimit` when requesting fee data from fee oracle, but then execute erc20 token bridging with this fee data. I don't know how exactly this can be used for malicious behavior, but we should split this into two different implementations of FeeHandlerWithOracle. With this approach, we can map exact implementation based on resourceID and domains inside fee router and not even worry about how this can be used for malicious activity.

## Testing details

- [ ] Refactor and expand unit test 

## Acceptance Criteria

- [ ] Have three different implementations of fee handler with oracle
- [ ] Passing unit tests

**Comment by P1sar** [comment]
We already have task for this. Or I am missing something? 
https://github.com/sygmaprotocol/sygma-solidity/issues/60
and PR 
https://github.com/sygmaprotocol/sygma-solidity/pull/120/files

**Comment by viatrix** [comment]
The issue #60 is just for Substrate. This issue also covers the generic message handling. I'll update the PR and reference this task in the PR
