### ISSUE TITLE
Percent based fee handler (EVM & substrate)

### ISSUE THREAD

**Issue by nmlinaric** [sygmaprotocol/sygma-solidity#188]
## Story
* As Sygma Operators
* We want Sygma to support fees based on a % of the transferred token amount
* So that we can charge users relative to the transferred amount

## Implementation details
Implement fee handler with dynamic % fee, based on token amount that is being bridged, not the USD value (current dynamic fee handler)

You can check out formal definition of this fee strategy [inside technical docs of relayer](https://github.com/sygmaprotocol/sygma-relayer/blob/main/docs/general/Fees.md).

**For now we only need to support collecting fees in ERC20 tokens (not base currency).**

## Testing details
Unit tests

## Acceptance criteria
[ ] Passing current unit and e2e tests
[ ] Passing unit tests that cover the new functionality

**Comment by alexmmueller** [comment]
Please find more information on the requirements [here](https://www.notion.so/chainsafe/Based-Fees-across-EVM-Substrate-ff15491c05e14843b7e020039b935384).

**Comment by itsbobbyzzz168** [comment]
@nmlinaric - fyi based on chat with @freddyli7 we'll bring this back into cycle 1 (as. p2) as i know you have your hands full atm. so we can chat about this in sprint sync.
