### ISSUE TITLE
Integrate Polygon

### ISSUE THREAD

**Issue by tcar121293** [sygmaprotocol/sygma-solidity#209]
**Network: Polygon**

**Environment: Mainnet**

# Preparation

- [x]  Prepare RPC endpoint for relayers & explorer
- [x]  Define all new routes and appropriate fee properties

## On Chain preparation

- [x]  **Deploy multisig account**
    - [x]  Deploy Super-Admin multisig account with all participants (gnosis multisig if applicable)
    - [x]  Save information to 1Password on deployed multisig
    - [x]  Top-up all multisig participants for a few transactions
- [x]  **TopUp Operational address**
    - [x]  `0x695bd50cb07ffbd4098b272ce8b52b3c256ca049`

# On-Chain Setup

- [x]  **Deploy contracts to the new Network**
    - [x]  Write migrations
    - [x]  Deploy contracts using the migrations
    - [x]  Configure supported resources on the new network
    - [x]  Renounce admin access
    - [x]  Verify all contracts
    - [x]  Execute after deployment checklist
- [x]  **Update the [deployment page](https://www.notion.so/Mainnet-deployment-b53c0e3624e84bc9a94f610687633945?pvs=21) with on-chain information**
- [ ]  **Create a PR updating environment information for Sygma docs**
- [x]  **Register new domain on other networks**
    - [x]  Create proposals for routes toward the new network using admin multisig
    - [x]  Proposals signed by the threshold of admins
    - [x]  Proposals executed
- [x]  **Top-up relayers execution addresses**
    - [x] Define balance-checker threshold
    - [x]  Phala relayer id 20: `0x34D92E33c9973277a83B105B1C45c9579F71C98E` 
    - [x]  Phala relayer id 21: `0x580549E46b62929182aCfbCB93544A0f213405a2` 
    - [x]  Bware relayer id 10: `0x8be30312f8eBc22F46c7f06F9913C52ef7690345` 
    - [x]  Bware relayer id 11: `0x181b05D98dCCB9e38cf51fd30F4A225De79A3366` 
    - [x]  Sygma relayer id 0: `0xa67bF22Df59071E57b0E345161bCDFcd436eD769`
    - [x]  Sygma relayer id 1: `0x8f18154c57D2AFB1E12224788b366c5Da17Ef3E7`
    - [x]  Sygma relayer id 2: `0x31404a0ece67Dd8b374C3088a76A5DcAC7D4BF37`

# Off-Chain Setup

## Update shared configuration

- [x]  Prepare PR with new shared configuration
- [x]  New shared configuration successfully resolving on well-known URL

## Update balance configuration

- [x]  Prepare PR with new balance configuration
- [x]  New balance configuration successfully resolving on well-known URL

### Relayers

- [x]  Prepare updated configuration for all relayers
- [x]  Update configs with the new network on AWS
- [x]  Communicate config changes to relaying partners
- [x]  Redeploy all relayers in this environment

### Explorer / Indexer

- [x]  Update configuration with new chain information
- [x]  Redeploy services

# QA testing
- [x]  **Execute transaction on newly opened route**
    - [x]  GMP | Ethereum → Polygon
    - [x]  GMP | Polygon → Ethereum
    - [x]  GMP | Base → Polygon
    - [x]  GMP | Polygon → Base
    - [x]  GMP | Cronos → Polygon
    - [x]  GMP | Polygon → Cronos
    - [x]  GMP | Gnosis → Polygon
    - [x]  GMP | Polygon → Gnosis

- [x]  **Merge docs PR with the updated environment information**

**Comment by tcar121293** [comment]
### On-chain preparation update
- contracts deployed on polygon
- contracts verified
- basicFeeHandler configured
- feeRouterHandler configured
- renounced role
```┌──────────────────────────────┬──────────────────────────────────────────────┐
│           (index)            │                    Values                    │
├──────────────────────────────┼──────────────────────────────────────────────┤
│       Deployer Address       │ '0x0aE5594F4b6833e488Bf6c4C9E94c246D90abfDb' │
│          Domain ID           │                     '7'                      │
│        Bridge Address        │ '0x73aB792E6AdF236879a0A2AB1597fa221E736a0d' │
│     ERC20Handler Address     │ '0x3eE20f17BC7D07bf3e06a7342C13A29823C22Ad5' │
│    ERC721Handler Address     │ '0xcBB24bb5AC8BA57C763800a3C1D55e2659637192' │
│  FeeRouterContract Address   │ '0x11947a868b304898e51E50371b84a34D278026e5' │
│   BasicFeeHandler Address    │ '0x823055b65894203e41EA35BaAC0E1862a9C07E6D' │
│ PercentageFeeHandler Address │ '0x2e1eE4153ad2F763ab8C612415AcF0DEe02Bc79B' │
└──────────────────────────────┴──────────────────────────────────────────────┘

**Comment by tcar121293** [comment]
All relayers are topped up with 10 MATIC
Here are the tx:
https://polygonscan.com/tx/0x141b2cce6233301ea15e8ebd8a8c0f3b1f064fe353324bebd7440fc2437988b2
https://polygonscan.com/tx/0x1cd2e6f88553d16a5174bcff69375ee8700ecc3bd0a371cd8b1d6ccf7e7a7dbc
https://polygonscan.com/tx/0x5a372e9130a35075f82ebd6c30cdb60bb8fd30612647e6e28482632b94a92230
https://polygonscan.com/tx/0x94ec0facc21e9bd7ceaf52f07e233365631ca367a6b8249a34ec649dc57e781e
https://polygonscan.com/tx/0x098d6d6c6e41c08c1b0c1eeb4419693e442ff92555e816ad03e4f63347ae441f
https://polygonscan.com/tx/0x2cd85fb1aac8da77e97cfefc463c4d04694e3fc3c0c0dfbcdd32f6c845c158f6
https://polygonscan.com/tx/0xeeae3bd1f57ce82ceeca027029146153c1e2eafc3d6ece867340e9439b49494b

**Comment by MakMuftic** [comment]
### New Routes:
| Type | Route                  | Fee       |
|------|------------------------|-----------|
| GMP  | Polygon -> Ethereum    | 20 MATIC  |
| GMP  | Polygon -> Base        | 2 MATIC   |
| GMP  | Polygon -> Cronos      | 1 MATIC   |
| GMP  | Polygon -> Gnosis      | 1 MATIC   |
| GMP  | Ethereum -> Polygon    | 0.0004 ETH|
| GMP  | Base -> Polygon        | 0.0004 ETH|
| GMP  | Cronos -> Polygon      | 25 CRO    |
| GMP  | Gnosis -> Polygon      | 1 xDAI   |

**Comment by LyonSsS** [comment]
QA Smoke tested all the routes via GMP on mainnet: 
1. ETH - Polygon https://scan.buildwithsygma.com/transfer/0xa09af7c5a491bbfd6e00bf601dac8f29885bf8ee85ebd77a15ec44b7c50dab9d 
2. Polygon - ETH https://scan.buildwithsygma.com/transfer/0xbc7461a41a90552621fedcd445735152a6120b2b7e727ab88b5c36323f88fdb9 
3. Cronos - Polygon https://scan.buildwithsygma.com/transfer/0x9821fbf0e36fb36e856ff0a939b49a1d32f41244a5df170ba6c3ee8e27be014f 
4. Polygon - Cronos https://scan.buildwithsygma.com/transfer/0xb78a63841b8493a66a412030f8f981df3ab4382325e732ffa4989697ccbfd9c7
5. Base - Polygon https://scan.buildwithsygma.com/transfer/0xf7702d4eea36f14a6d160893f5740669ce69d66044d3a89e5e499efc58584fc4 
6. Polygon - Base https://scan.buildwithsygma.com/transfer/0xf7702d4eea36f14a6d160893f5740669ce69d66044d3a89e5e499efc58584fc4
7. Gnossis - Polygon https://scan.buildwithsygma.com/transfer/0x333cb1072b49ac60f63a008b0da399214847c8f96b1ad32d7634f03a837d64f7 
8. Polygon - Gnossis https://scan.buildwithsygma.com/transfer/0x3b18baaf14210467c35be09619622669c556d9cd7b0f017c2a0fe01409919165 
Fees and behavior all work as expected. Ticket can now be closed
