### ISSUE TITLE
Migration script not registering newly added network to the fee router

### ISSUE THREAD

**Issue by mpetrun5** [sygmaprotocol/sygma-solidity#42]
When we deploy contracts to a new network, we register fee handlers on the fee router per domain, but the existing network doesn't know about the new network and doesn't have fee handlers set.

## Expected Behavior

When deploying a new network, fee handlers for that domain on other networks should also be registered.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Versions
ChainBridge commit (or docker tag): 
chainbridge-solidity version:
chainbridge-substrate version:
Go version:

**Comment by nmlinaric** [comment]
Closing this since in the majority of cases function call access for registering domains is on a multisig and has to be done manually.
