### ISSUE TITLE
Refactor generic resource registration

### ISSUE THREAD

**Issue by MakMuftic** [sygmaprotocol/sygma-solidity#66]
Currently, `IGenericHandler` defines the function signature that should be used for registering resources.

```
function setResource(
        bytes32 resourceID,
        address contractAddress,
        bytes4 depositFunctionSig,
        uint depositFunctionDepositorOffset,
        bytes4 executeFunctionSig,
) external;
```

Considering our new generic handler, this interface doesn't make sense anymore.

## Implementation details

TBD

## Testing details

TBD

## Acceptance Criteria

TBD

**Comment by MakMuftic** [comment]
Implementation depends on this question: **Should we support the generic handler's old implementation (permissioned)?** @P1sar @mpetrun5 @nmlinaric, what do you think about this support?

If yes, we can have different methods for registering old and new handlers or figure out what minimal changes to the old handler are needed to unify the interface (maybe differentiate handler registration and resource registration).

**Comment by mpetrun5** [comment]
This is also a question of weird handlers that we might plan to include in the future and do we need some more generic registration of resources for all future handlers as we might run into a case that the current registration does not support.
Do we have a case for some blob of data registration that then the handler parses into params it needs.

**Comment by P1sar** [comment]
hm. But we do not need any registerResourceID methods for new generic handler since it is permissionless?
