### ISSUE TITLE
Update `FeeHandlerWithOracle` to support dynamic fees for permissionless generic handler

### ISSUE THREAD

**Issue by MakMuftic** [sygmaprotocol/sygma-solidity#71]
As the gas limit for the destination chain will be defined as a parameter in the new message format, we need to update `FeeHandlerWIthOracle` to support parsing this parameter and calculating tx cost.

## Implementation details

We will add a new param to oracle message (`msgGasLimit`) which will be parsed by `FeeHandlerWithOracle` and tx cost is calculated with that value - not like before, where we used a variable from the contract (that has a public setter).

********************************Old formula for destination gas:********************************

`destTxCost = oracleDestGasPrice * contractGasLimit * oracleMessage.ter / 1e18`

********************************New formula for destination gas:********************************

`destTxCost = oracleDestGasPrice * messageGasLimit * oracleMessage.ber / 1e18`

## Testing details

- Add unit tests for new fee handler

## Acceptance Criteria

- [ ] Add new fee handler
- [ ] Passing unit tests
- [ ] Passing e2e locally with new version of fee handler

**Comment by P1sar** [comment]
I checked it should be 
`destTxCost = oracleDestGasPrice * messageGasLimit * oracleMessage.ber / 1e18` (changed ter to ber)
https://github.com/sygmaprotocol/sygma-solidity/blob/master/contracts/handlers/fee/FeeHandlerWithOracle.sol#L28
